[mcp_servers.serena]
command = "uvx"
args = ["--from", "serena-agent", "serena-mcp-server", "--transport", "stdio", "--project", "."]

[mcp_servers.codacy]
command = "npx"
args = ["-y", "@codacy/codacy-mcp"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp", "--api-key", "$CONTEXT7_API_KEY"]
